import Foundation

/// User-selectable web icon library used in code generated by the conversion
/// and refinement pipelines.
///
/// SF Symbols only render in Apple UIs, so the *generated* HTML/React needs a
/// real web icon set. The selected library drives two things:
///
/// 1. **Prompt guidance** — `SketchAnalysisPrompt.buildIconLibrarySection(_:)`
///    tells the model which library's markup conventions and import paths to
///    use, so generated `htmlPreview` and `reactCode` are consistent.
/// 2. **Preview runtime** — `HTMLTemplateEngine.injectIconLibrary(into:library:)`
///    splices the corresponding `<script>` or `<link>` tag into the
///    model-generated HTML so libraries like Lucide / Phosphor / Material
///    Symbols actually render in the WKWebView preview. Heroicons and Carbon
///    are emitted as inline SVGs and need no runtime asset.
///
/// The choice is generation-time only: changing libraries does **not** rewrite
/// existing previews; only the next conversion or refinement will use the new
/// library. See the `claude/document-iconography-zLGJk` plan for context.
enum IconLibrary: String, Codable, Sendable, CaseIterable, Identifiable {
    case none
    case lucide
    case phosphor
    case heroicons
    case materialSymbols
    case carbon

    var id: String { rawValue }

    /// Whether this option means "skip icon guidance entirely". Used by the
    /// prompt builder to no-op and by `DesignSystem.isEmpty` to decide whether
    /// an icon-only choice should surface a design-system section.
    var isNone: Bool { self == .none }

    // MARK: - Display

    var displayName: String {
        switch self {
        case .none:            return "None"
        case .lucide:          return "Lucide"
        case .phosphor:        return "Phosphor Icons"
        case .heroicons:       return "Heroicons"
        case .materialSymbols: return "Material Symbols"
        case .carbon:          return "Carbon Icons"
        }
    }

    /// One-line description shown beneath the picker.
    var blurb: String {
        switch self {
        case .none:
            return "No icon library — the model will only emit icons if the sketch shows them."
        case .lucide:
            return "Clean, consistent open-source icons from the Lucide community."
        case .phosphor:
            return "Flexible icon family with thin, regular, bold, and duotone weights."
        case .heroicons:
            return "Tailwind Labs' outline and solid icons, inlined as SVG."
        case .materialSymbols:
            return "Google's Material Symbols, loaded as a variable icon font."
        case .carbon:
            return "IBM's Carbon Design System icons on a 16/20/24/32 grid, inlined as SVG."
        }
    }

    /// SF Symbol used as the visual chip in the iOS picker. Has nothing to do
    /// with what gets rendered in the web preview.
    var pickerSymbol: String {
        switch self {
        case .none:            return "circle.slash"
        case .lucide:          return "circle.grid.3x3"
        case .phosphor:        return "leaf"
        case .heroicons:       return "h.square"
        case .materialSymbols: return "m.square"
        case .carbon:          return "atom"
        }
    }

    // MARK: - Runtime integration

    /// How (or whether) the library is delivered at runtime.
    enum Integration: String, Sendable {
        /// No injection — `headTags` is empty.
        case none
        /// A `<script>` tag in `<head>`. May also need `initScript` to wire up
        /// markup-to-icon replacement (e.g. Lucide's `createIcons`).
        case cdnScript
        /// A `<link rel="stylesheet">` in `<head>`. Activates a webfont
        /// (Material Symbols) or class-based CSS (Phosphor delivers its CSS via
        /// the script bundle, so it stays in `.cdnScript`).
        case cdnStylesheet
        /// No runtime asset — the model must inline SVGs that follow the
        /// library's house style.
        case inlineSVG
    }

    var integrationKind: Integration {
        switch self {
        case .none:            return .none
        case .lucide:          return .cdnScript
        case .phosphor:        return .cdnScript
        case .heroicons:       return .inlineSVG
        case .materialSymbols: return .cdnStylesheet
        case .carbon:          return .inlineSVG
        }
    }

    /// The exact `<script>` / `<link>` markup to inject into `<head>` for this
    /// library. Empty string when no runtime asset is required.
    var headTags: String {
        switch self {
        case .none, .heroicons, .carbon:
            return ""
        case .lucide:
            return #"<script src="https://unpkg.com/lucide@latest"></script>"#
        case .phosphor:
            return #"<script src="https://unpkg.com/@phosphor-icons/web"></script>"#
        case .materialSymbols:
            return #"<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0">"#
        }
    }

    /// Optional script that runs after the body to swap markup placeholders
    /// with real icons. `nil` when the library renders directly via CSS or
    /// inline markup.
    var initScript: String? {
        switch self {
        case .lucide:
            // `lucide.createIcons()` scans for `<i data-lucide="...">` and
            // replaces each with an SVG. Idempotent — safe to re-run.
            return #"<script>if (window.lucide) { lucide.createIcons(); }</script>"#
        case .none, .phosphor, .heroicons, .materialSymbols, .carbon:
            return nil
        }
    }

    // MARK: - Prompt guidance

    /// React-side import path for the chosen library, surfaced in the prompt
    /// so generated `reactCode` resolves correctly. `nil` for libraries that
    /// don't have a single canonical Next.js package convention.
    var reactImportHint: String? {
        switch self {
        case .lucide:
            return #"import { Search } from "lucide-react""#
        case .phosphor:
            return #"import { MagnifyingGlass } from "@phosphor-icons/react""#
        case .heroicons:
            return #"import { MagnifyingGlassIcon } from "@heroicons/react/24/outline""#
        case .materialSymbols:
            // Material Symbols is normally used via the font; in React most
            // teams just emit a `<span class="material-symbols-outlined">`.
            return nil
        case .carbon:
            return #"import { Search } from "@carbon/icons-react""#
        case .none:
            return nil
        }
    }

    /// Markup convention and one or two examples, expanded into the prompt by
    /// `SketchAnalysisPrompt.buildIconLibrarySection(_:)`.
    var promptGuidance: String {
        switch self {
        case .none:
            return "Do not add icons unless the sketch clearly shows one. If you must, inline a simple SVG."

        case .lucide:
            return """
            For htmlPreview, use `<i data-lucide="<icon-name>" class="size-5"></i>` (e.g. `data-lucide="search"`, `data-lucide="menu"`, `data-lucide="chevron-right"`). The host page loads the Lucide runtime and calls `lucide.createIcons()` automatically — just emit the markup.
            For reactCode, import named components from `lucide-react` (e.g. `import { Search, Menu, ChevronRight } from "lucide-react"`) and render `<Search className="size-5" />`.
            """

        case .phosphor:
            return """
            For htmlPreview, use `<i class="ph ph-<icon-name> text-xl"></i>` (e.g. `ph-magnifying-glass`, `ph-list`, `ph-caret-right`). Optionally swap `ph` for `ph-bold`, `ph-fill`, or `ph-duotone` to change weight. The host page loads `@phosphor-icons/web`, which auto-styles the markup.
            For reactCode, import from `@phosphor-icons/react` (e.g. `import { MagnifyingGlass, List, CaretRight } from "@phosphor-icons/react"`) and render `<MagnifyingGlass size={20} />`.
            """

        case .heroicons:
            return """
            Inline the SVG verbatim in the Heroicons house style: 24×24 viewBox, `fill="none"`, `stroke="currentColor"`, `stroke-width="1.5"`, `stroke-linecap="round"`, `stroke-linejoin="round"`, sized with `class="size-5"`. Use solid variants only when the sketch shows a filled glyph (`fill="currentColor"`, no stroke).
            For reactCode, import from `@heroicons/react/24/outline` (e.g. `import { MagnifyingGlassIcon } from "@heroicons/react/24/outline"`) and render `<MagnifyingGlassIcon className="size-5" />`. Use `/24/solid` for filled glyphs.
            """

        case .materialSymbols:
            return """
            For htmlPreview, use `<span class="material-symbols-outlined">search</span>` with the glyph name as the element's text content (e.g. `search`, `menu`, `chevron_right`). Size via Tailwind text utilities (`text-xl`, `text-2xl`). The host page loads the Material Symbols Outlined webfont.
            For reactCode, render the same `<span className="material-symbols-outlined">search</span>` markup — no React package import is required.
            """

        case .carbon:
            return """
            Inline the SVG verbatim in the Carbon Icons house style: square viewBox on the 16/20/24/32 grid (most icons use `viewBox="0 0 32 32"`), `fill="currentColor"`, `aria-hidden="true"`, sized with `class="size-5"`. Do not stroke; Carbon glyphs are filled paths.
            For reactCode, import from `@carbon/icons-react` (e.g. `import { Search } from "@carbon/icons-react"`) and render `<Search size={20} />`.
            """
        }
    }
}
